[Project]
Name = 'w-tcp-proxy'
Port = 2000

[Log]
Console = true
ConsoleLevel = 'debug'
File = true
FileLevel = 'debug'

[[Backends]]
Id = '0'
Address = '192.168.0.1'
Default = true
[[Backends]]
Id = '1'
Address = '192.168.0.2'
Default = false

[[Route]]
Key = 'key0'
BackendId = ['0', '1']
[[Route]]
Key = 'key1'
BackendId = ['0']
