[project]
name="w-tcp-proxy"

[log]
to="file"
level="debug"

[metric]

[[backend]]
address="10.71.20.181"
label=0
default=true

[[backend]]
address="10.71.20.6"
label=1

[[rule]]
code="code0"
backend=[0,1]

[[rule]]
code="code1"
backend=[0]
