[Project]
Name = 'w-tcp-proxy'
Port = 2000

[Log]
Console = true
# info, debug
ConsoleLevel = 'debug'
File = true
FileLevel = 'info'

[[Backends]]
Id = '0'
Address = '192.168.122.1:22'
Default = true

[[Route]]
Key = 'key0'
Type = 'copy'
